### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by MyNameLx** [gxvv/ex-baiduyunpan#23] opened 2018-03-14 14:02 UTC
Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by gxvv** [comment] 2018-03-14 14:45
Duplicate of #9

**Closed by gxvv** 2018-03-14 14:45 UTC
