### ISSUE TITLE
EX-baiduyunpan:程序异常

### ISSUE THREAD

**Issue by LiuChengqian90** [gxvv/ex-baiduyunpan#24] opened 2018-03-16 01:56 UTC
请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.2.0

TemperMonkey Ver: 4.6.5709

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

**Comment by gxvv** [comment] 2018-03-16 06:51
Duplicate of #9

**Closed by gxvv** 2018-03-16 06:51 UTC
