### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by handongccc** [gxvv/ex-baiduyunpan#89] opened 2018-05-03 10:24 UTC
Script Ver: 0.1.7

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

**Comment by gxvv** [comment] 2018-05-03 14:01
Duplicate of #63

**Closed by gxvv** 2018-05-03 14:01 UTC
