### ISSUE TITLE
js加载失败

### ISSUE THREAD

**Issue by blurHY** [gxvv/ex-baiduyunpan#93] opened 2018-05-06 04:10 UTC
Exception: **downloadManager.js加载失败**
Script Ver: 0.1.8
TemperMonkey Ver: 4.6.5757
UA: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by gxvv** [comment] 2018-05-06 13:42
Duplicate of #63

**Closed by gxvv** 2018-05-06 13:42 UTC
